---
collections:
  - containers.podman
  - devsec.hardening
  - ansible.posix
  - fedora.linux_system_roles
  - epfl_si.rhel
  - ansible.windows
  - community.windows
  - ansible.windows
  - servicenow.itsm
