---
collections:
  - community.vmware
  - vmware.vmware_rest
  - awx.awx
  - containers.podman
  - ansible.posix
  - fedora.linux_system_roles
  - epfl_si.rhel
  - infra.ah_configuration
  - infra.controller_configuration
  - redhat_cop.controller_configuration
  - community.general
  - ansible.windows
  - chocolatey.chocolatey
  - community.windows
  - ansible.windows
  - dynatrace.oneagent
  - servicenow.itsm
