---
- name: RHEL deploy Zabbix Agent
  hosts: all
  become: yes
  vars:
    installer_url: 'https://repo.zabbix.com/zabbix/7.4/release/rhel/9/noarch/zabbix-release-latest.el9.noarch.rpm'
    zabbix_server: 'REPLACE_ME'

  tasks:
  - name: Install required repo
    ansible.builtin.dnf:
      name: '{{ installer_url }}'
      state: present
      disable_gpg_check: true

  - name: Install required packages
    ansible.builtin.dnf:
      name:
        - zabbix-agent2
        - firewalld
      state: present

  - name: Set Zabbix Server permission
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      search_string: 'Server=127.0.0.1'
      line: 'Server={{ zabbix_server }}'
      backup: true

  - name: Set Active Agent
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      search_string: 'ServerActive=127.0.0.1'
      line: 'ServerActive={{ zabbix_server }}'
      backup: true
      
  - name: Set Agent Hostname
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      search_string: 'Hostname=Zabbix server'
      line: 'Hostname={{ inventory_hostname }}'
      backup: true

  - name: Config Zabbix Agent as root
    ansible.builtin.lineinfile:
      path: /usr/lib/systemd/system/zabbix-agent2.service
      search_string: 'User=zabbix'
      line: 'User=root'
      backup: true
      
  - name: Enable and activate the service
    ansible.builtin.systemd:
      name: zabbix-agent2
      enabled: true
      state: restarted

  - name: Enable firewald service to start on boot up
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: true

  - name: Create firewall rule for application
    ansible.posix.firewalld:
      service: zabbix-agent
      permanent: true
      state: enabled
      immediate: true
