---
- name: Recover from unresponsive device
  hosts: bastion
  gather_facts: false
  vars:
    tags_parsed: {}
 
  tasks:
  - name: Build the dictionary
    ansible.builtin.set_fact:
      tags_parsed: >-
        {{
          tags_parsed | combine({
            (item.split(':', 1)[0]): (item.split(':', 1)[1] if ':' in item else true)
          })
        }}
    loop: "{{ tags.split(',') }}"  

  - name: Identify the Switch/Host
    ansible.builtin.set_fact:
      vm_name: "{{ tags_parsed.device_hostname }}"
  
  - name: Identify Hypervisor
    ansible.builtin.set_fact:
      _hypervisor: "{{ tags_parsed.agent_host }}"
      
  - name: "Issue a graceful reboot"
    ansible.builtin.shell: "ifconfig"
    register: reboot_result
    changed_when: "'is being rebooted' in reboot_result.stdout"
