---
- name: Manage Cisco Switch
  hosts: all
  gather_facts: false
  vars:
    targer_interface: "GigabitEthernet0/{{ interface_index }}"
 
  tasks:
  - name: Administratively Enable Interfaces on Switch
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ targer_interface }}"
          enabled: true
      state: merged
