---
- name: Manage Cisco Switch
  hosts: all
  gather_facts: false
  vars:
    targer_interface: "GigabitEthernet0/2"
    #targer_interface: "GigabitEthernet0/{{ interface_index }}"
 
  tasks:
  - name: Debug
    ansible.builtin.debug:
      var: "{{ test[0] }}"
