---
- name: Create ServiceNow Incident from EDA event
  hosts: localhost
  gather_facts: no
  vars:
    tags_parsed: {}  

  tasks:
  - name: Build the dictionary
    ansible.builtin.set_fact:
      tags_parsed: >-
        {{
          tags_parsed | combine({
            (item.split(':', 1)[0]): (item.split(':', 1)[1] if ':' in item else true)
          })
        }}
    loop: "{{ tags.split(',') }}"  

  - name: Get the Node IP
    ansible.builtin.set_fact:
      switch: "{{ tags_parsed.source_host }}"

  - name: Enable Interfaces on Switch
    cisco.ios.ios_command:
      commands: "show logging"
    register: switch_logs
    delegate_to: "{{ switch }}"

  - name: Convert the last 20 log lines into a single text block
    ansible.builtin.set_fact:
      formatted_logs: "{{ switch_logs.stdout_lines[0][-20:] | join('\n') }}"
        
  - name: Create a ServiceNow Incident
    servicenow.itsm.incident:
      instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"    
      state: new
      caller: "ansible"
      urgency: high
      impact: high
      short_description: "Monitoring Alert - {{ ansible_eda.event.payload.alert_title }}"
      description: "{{ formatted_logs }}"
    register: new_ticket

  - name: ServiceNow Ticket Number
    ansible.builtin.debug:
      var: new_ticket.record.number
    when: new_ticket is defined
