---
- name: Create ServiceNow Incident from EDA event
  hosts: '{{ _hosts }}'
  gather_facts: no
  become: true

  tasks:      
  - name: Create a ServiceNow Incident
    servicenow.itsm.incident:
      instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"    
      state: new
      caller: "ansible"
      urgency: high
      impact: high
      short_description: "Monitoring has identified a problem on {{ _hosts }}"
      description: "{{ _payload }}"
    register: new_ticket

  - name: ServiceNow Ticket Number
    ansible.builtin.debug:
      var: new_ticket.record.number
    when: new_ticket is defined
