---
- name: Handle EDA Payload and Initial Tasks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Parse string to scope_dict
      ansible.builtin.set_fact:
        scope_dict: "{{ dict(scope.split(',') | map('split', ':')) }}"
      when: scope is defined
            
    - name: Get device name
      ansible.builtin.set_fact:
        device_name: "{{ scope_dict.snmp_device }}"

- name: Automated Incident Response - Cisco Switch Unauthorized Config Change
  hosts: "{{ hostvars['localhost']['device_name'] }}"
  gather_facts: false
  
  tasks:
  - name: Gather recent logs from the Cisco switch
    cisco.ios.ios_command:
      commands: 
        - "show archive log config all"
    register: switch_logs

  - name: Convert the last 20 log lines into a single text block
    delegate_to: localhost
    connection: local
    ansible.builtin.set_fact:
      formatted_logs: "{{ switch_logs.stdout_lines[0][-20:] | join('\n') }}"
      
  - name: Create a ServiceNow Incident
    delegate_to: localhost
    connection: local
    servicenow.itsm.incident:
      instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"    
      state: new
      caller: "ansible"
      urgency: high
      impact: high
      short_description: "Monitoring Alert - {{ ansible_eda.event.payload.alert_title }}"
      description: "{{ formatted_logs }}"
    register: new_ticket

  - name: ServiceNow Ticket Number
    delegate_to: localhost
    connection: local
    ansible.builtin.debug:
      var: new_ticket.record.number
    when: new_ticket is defined
