---
- name: Respond to Datadog Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35001

  rules:
    - name: Datadog Alert - Web Monitoring
      condition: (event.payload.alert_type == "error") and (event.payload.alert_title == "Web App is DOWN")
      action:
        run_job_template:
          name: "EDA - Linux Deploy APP With Podman"
          organization: Default
          job_args:
            limit: "{{ event.payload.hostname }}"

    - name: Datadog - SNMP Alert Host Down
      condition: (event.payload.alert_type == "error") and (event.payload.alert_tags is search ("device_down"))
      action:
        run_job_template:
          name: "EDA - Restart Switch"
          organization: Default
          job_args:
            extra_vars: 
              tags: "{{ event.payload.alert_tags }}"
              
    - name: Datadog - SNMP Alert Interface Down
      condition: (event.payload.alert_type == "error") and (event.payload.alert_tags is search ("interface_down"))
      action:
        run_job_template:
          name: "EDA - Network Config"
          organization: Default
          job_args:
            extra_vars: 
              tags: "{{ event.payload.alert_tags }}"
              scope: "{{ event.payload.scope }}"

    - name: "Datadog - Log Alert: Config Mode"
      condition: (event.payload.alert_type == "error") and (event.payload.alert_tags is search ("config_change"))
      action:
        run_job_template:
          name: "EDA - Report Incident to ServiceNow"
          organization: Default
          job_args:
            extra_vars: 
              tags: "{{ event.payload.alert_tags }}"
              scope: "{{ event.payload.scope }}"
