---
- name: Respond to Datadog Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35001

  rules:
    - name: Datadog Alert - Web Monitoring
      condition: (event.payload.alert_type == "error") and (event.payload.alert_title == "Web App is DOWN")
      action:
        run_job_template:
          name: "EDA - Linux Deploy APP With Podman"
          organization: Default
          job_args:
            limit: "{{ event.payload.hostname }}"
          
    - name: Datadog Alert - SNMP Metric
      condition: 
        all:
          - event.payload.alert_type == "error" 
          - event.payload.alert_title is match ("SNMP Interface Status Alert")
      action:
        run_job_template:
          name: "EDA - Linux Deploy APP With Podman"
          organization: Default
          job_args:
            limit: "{{ event.payload.hostname }}"
