---
- name: Listen to Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35002

  rules:
    - name: Print Payload
      condition: event.payload is defined
      action:
        debug:
          var: event.payload
