---
- name: Respond to Dynatrace
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35002

  rules:
    - name: Dynatrace Problem Alerts
      condition: ((event.payload.State == "OPEN") and (event.payload.ProblemTitle == "Http monitor outage"))
      action:
        run_job_template:
          name: "{{ template }}"
          organization: Default
          job_args:
            limit: "{{ event.payload.EntityName }}"
            extra_vars:
              url: "{{ event.payload.EntityName }}"
          
