---
- name: Respond to FIM Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35002

  rules:
    - name: FIM Alerts - DevSec managed file has changed
      condition: ((event.payload.event.labels[0] == "devsec") and (event.payload.event.operation is match('write',ignorecase=true)) or (event.payload.event.operation is match('remove',ignorecase=true)))       
      action:
        run_workflow_template:
          name: "WORKFLOW - Redeploy DevSec Role"
          organization: Default
          
    - name: Debug
      condition: event.payload is defined       
      action:
        debug:
          var: event.payload
          
