---
- name: Respond to ServiceNow Events
  hosts: all
  sources:
    - ansible.eda.webhook:

  rules:
    - name: ServiceNow Change Request set to Scheduled
      condition: event.payload.event_type == "change_request_scheduled"
      action:
        run_job_template:
          name: "RHEL ServiceNow - Apply Updates"
          organization: Default
          job_args:
            limit: "{{ event.payload.change_ticket.title.split(':')[1] | replace(' ', '') }}"
            extra_vars:
              data: "{{ event.payload.change_ticket.title.split(':')[1] | replace(' ', '') }}"

    - name: Print Payload
      condition: event.payload is defined
      action:
        debug:
          var: event.payload
