---
- name: Respond to ServiceNow Events
  hosts: all
  sources:
    - ansible.eda.webhook:

  rules:
    - name: ServiceNow Change Request set to Scheduled
      condition: (event.payload.event_type == "change_request_scheduled") and (event.payload.change_ticket is search ("Pending OS Updates"))  
      action:
        run_job_template:
          name: "EDA - Linux Deploy APP With Podman"
          organization: Default
          job_args:
            extra_vars:
              data: "{{ event.payload.change_ticket.title.split(':')[1] | replace(' ', '') }}"

    - name: Print Payload
      condition: event.payload is defined
      action:
        debug:
          var: event.payload
