---
- name: Respond to Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35001

  rules:
    - name: ServiceNow Events
      condition: event.payload.event_type == "change_request_scheduled"
      action:
        run_job_template:
          name: "RHEL ServiceNow - Apply Updates"
          organization: Default
          job_args:
            limit: "{{ event.payload.change_ticket.title.split(':')[1] | replace(' ', '') }}"
            extra_vars: 
              data: "{{ event.payload }}"
