---
- name: Respond to Zabbix Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35001

  rules:
    - name: Zabbix Alert - SELinux Change
      condition: event.payload.trigger_name is match('Security Alert DevSec',ignorecase=true)
      action:
        run_job_template:
          name: "LINUX Workshop - OS Hardening"
          organization: Default
          job_args:
            extra_vars:
              _hosts: "{{ event.payload.host_host }}"
