---
- name: Update all packages on RHEL
  hosts: all
  become: true
  vars:
    excluded_pks: "kernel*"
  
  tasks:
  - name: Update all installed packages using DNF module
    ansible.builtin.dnf:
      name: '*'
      state: latest
      exclude: '{{ excluded_pks }}'
      update_cache: true
      update_only: true
    register: dnf_update_status
  
  - name: Check to see if we need a reboot
    ansible.builtin.command: needs-restarting -r
    register: result
    ignore_errors: true
  
  - name: Reboot when required
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible"
    when: result.rc == 1
