---
- name: Run Updates on Windows
  hosts: windows
    
  tasks:
  - name: Windows Update List
    ansible.windows.win_updates:
      state: searched
    register: search_results
    
  - name: Report results
    ansible.builtin.debug:
      msg: "{{ search_results }}"
