---
- name: Add a user to a Windows
  hosts: windows
  gather_facts: false
  
  tasks:
    - name: Add User
      ansible.windows.win_user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        fullname: "{{ user_fullname }}"
        description: "{{ user_description }}"
        groups: "{{ user_groups }}"
        state: present
      register: result
      
    - name: Print results of the user task
      ansible.builtin.debug:
        msg: "{{ result }}"
