---
- name: Add a user to a Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Add User
      ansible.windows.win_user:
        name: "{{ win_user_name }}"
        password: "{{ win_user_password }}"
        fullname: "{{ win_user_fullname }}"
        description: "{{ win_user_description }}"
        groups: "{{ win_user_groups }}"
        state: present
      register: result
      
    - name: Print results of the user task
      ansible.builtin.debug:
        msg: "{{ result }}"
