---
- name: Run PowerShell
  hosts: windows
  gather_facts: false

  tasks:
    - name: Run PowerShell
      ansible.windows.win_powershell:
        script: |
          {{ ps_script }}
      register: ps_output

    - name: Print output of PS script
      ansible.builtin.debug:
        msg: "{{ ps_output }}"
