---
- name: RHEL misc config management
  hosts: all
  become: yes
  vars:
    oneagent_path: '/tmp/Dynatrace-OneAgent.sh'
 
  tasks: 
  - name: Install required packages
    ansible.builtin.dnf:
      name: firewalld
      state: present

  - name: Download Dynatrace Agent
    ansible.builtin.get_url:
      url: '{{ oneagent_installer_url }}'
      dest: '{{ oneagent_path }}'
      mode: '0600'
      headers: 
        Authorization: Api-Token {{ oneagent_paas_token }}
      
  - name: Enable services to start on boot up
    ansible.builtin.service:
      name: firewalld
      enabled: true
      state: started
      
  - name: Install agent
    ansible.builtin.command:
      argv:
        - /bin/sh
        - "{{ oneagent_path }}"
        - --set-monitoring-mode=fullstack
        - --set-app-log-content-access=true
        - --set-host-group=cmedeiro
        - --set-host-tag=workshop
        - --set-host-name="{{ inventory_hostname }}"
