---
- name: Deploy Webserver (Apache) on RHEL
  hosts: all
  become: yes
 
  tasks:
  - name: Install httpd and firewald packages
    ansible.builtin.package:
      name:
        - httpd
        - mod_ssl
        - firewalld
      state: present
 
  - name: Enable httpd and firewald service to start on boot up
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
      state: started
    loop:
      - httpd
      - firewalld
      
  - name: Create firewall rule for httpd service
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true

  - name: Copy a custom index.html file
    ansible.builtin.copy:
      src: ../files/index.html
      dest: /var/www/html/index.html

  - name: Reload httpd service if required
    ansible.builtin.service:
      name: httpd
      state: reloaded
      
  - name: Print the gateway for each host
    ansible.builtin.debug:
      msg: The application and be accessed on this url http://{{ public_dns_name }}
