---
- name: Deploy App on RHEL Using Podman
  hosts: all
  become: true
  
#  vars:
#    - app_name: "tasks-app"
#    - app_image: "quay.io/cmedeiro/tasks-app:latest"
#    - app_ports: "8080:8080"
 
  tasks:
  - name: Install podman and firewald packages
    ansible.builtin.package:
      name:
        - podman
        - firewalld
      state: present
  
  - name: Deploy application using podman
    containers.podman.podman_container:
      name: "{{ app_name }}"
      image: "{{ app_image }}"
      ports:
        - "{{ app_ports }}" 

  - name: Enable firewald service to start on boot up
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: true
    
  - name: Create firewall rule for application
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true
      
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: The application and be accessed on this url http://{{ public_dns_name }}
