---
- name: RHEL deploy Zabbix Agent
  hosts: all
  become: yes
  vars:
    installer_url: 'https://repo.zabbix.com/zabbix/7.0/rhel/9/x86_64/zabbix-release-7.0-5.el9.noarch.rpm'
     
  tasks: 
  - name: Install required packages
    ansible.builtin.dnf:
      name: installer_url
      state: present
