---
- name: Setup Controller for Workshop
  hosts: all
  gather_facts: false

  tasks:
    - name: Create AWS EC2 Credential
      ansible.controller.credential:
        name: "AWS EC2 Credential"
        credential_type: "AWS Web Services"
        organization: Default
        state: present
        inputs:
          username: "{{ aws_username }}"
          password: "{{ aws_password }}"
