---
- name: Install and configure NFS Server
  hosts: all
  become: true
#  vars:
#    nfs_server_exports:
#      - /var/lib/nfs1 10.95.95.2 (rw,anonuid=1000,anongid=1000)

  roles:
    - name: Install and configure NFS server
      role: epfl_si.rhel.nfs_server
