---
- hosts: all
  become: yes
  
  tasks:
  - name: Update all installed packages using DNF module
    ansible.builtin.dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: dnf_update_status
  
  - name: check to see if we need a reboot
    ansible.builtin.command: needs-restarting -r
    register: result
    ignore_errors: yes
  
  - name: Reboot when required
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible"
    when: result.rc == 1
