---
- hosts: all
  become: yes
  
  tasks:
  - name: Update all installed packages using DNF module
    ansible.builtin.dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: dnf_update_status
  
  - name: Reboot when packages were updated
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible"
    when: dnf_update_status.changed
